apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image:  401650335237.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest
        ports:
        - containerPort: 80
        env:
        - name: FLASK_ENV
          value: "production"