apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80  # Exposed port
    targetPort: 80  # Container port
  type: LoadBalancer  # Use LoadBalancer for external access (for cloud environments)